ci: run `npx svelte-kit sync` to fix warnings on CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,6 +49,10 @@ jobs:
       - name: Lint
         run: npm run lint
 
+      - name: Svelte Sync
+        if: success() || failure() # Run even if previous failed
+        run: npx svelte-kit sync
+
       - name: Svelte Check
         if: success() || failure() # Run even if previous failed
         run: npm run check
