:green_heart: ci: make some steps to run even previous one had failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,20 +43,22 @@ jobs:
 
       - name: Install dependencies
         run: pnpm install --frozen-lockfile
+
+      - name: Lint
+        run: npm run lint
       
       # Build Frontend
       - name: Build Frontend
+        if: success() || failure() # Run even if previous failed
         run: npm run build
 
       # Need to check only after build, so SvelteKit would generate files.
       - name: Svelte Check
         run: npm run check
 
-      - name: Lint
-        run: npm run lint
-
       # Cache Playwright
       - name: Cache Playwright
+        if: success() || failure() # Run even if previous failed
         uses: actions/cache@v3
         id: playwright_cache
         with:
